markdown: kramdown
kramdown:
  toc_levels: 2..6
title: CS 180 Portfolio - Rebecca Dang
description: Projects from Computational Photography and Computer Vision at UC Berkeley
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
